### ISSUE TITLE
install instructions are vague

### ISSUE THREAD

**Issue by nerd190** [pforret/crontask#1]
hi, this looks great, install info isnt too clear though, do I symlink `crontab2.sh` -> `/usr/bin/ct` or use the `ct` binary already in the repo instead?
Thank you

**Comment by pforret** [comment]
Hi! crontask is one of my older scripts and when I started looking through the code, I shivered.
That's why I just updated `crontask` to version 3, using the latest [bashew](https://github.com/pforret/bashew) template.
It's just new, so the paint is still wet, but it should be much easier to maintain, bugfix and add features now.

The general idea is: 

1. get the code with `basher` or `git clone`
2. optionally link the crontask.sh to your /usr/bin or /usr/local/bin (easier to remember)
3. add the script to your crontab as `/usr/bin/crontask cmd "some command to execute"` or `/usr/bin/crontask url "https://example.com/path/page"`

**Comment by pforret** [comment]
https://github.com/pforret/crontask/releases/tag/v3.0.0

**Comment by nerd190** [comment]
Thank you! the repo looks fresh and alot clearer now on installation!
I look forward to using this ingenious utility (webhooks on fail/success ?!?! thank you!)

**Comment by pforret** [comment]
Generic webhooks made more sense.
Feel free to send me your feedback and suggestion!

Also check the other bashew tools: https://github.com/topics/bashew ,
there might be more that you can use!

Peter
